---
title: "Lab 01 - Hello R"
author: "dalal salman alshamri"
date: "1/2/2021"
output: html_document
---

University ID: 2201003144

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Lab Exercise

(head( datasaurus _dozen)n y-numbers are greater than x and the 
summary( datasaurus _dozen)is 1846 long).)
code:
circle_data <-datasaurus_dozen %>%
 filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
geom_point()


##answer for task2
(correlation coefficient = -0.0645) in dion 
(the graph like dinosaur)
##answer for task4
(correlation coefficient = 0,0683) in circle
(the graph like circle)
(correlation coefficient = 0.0630) in circle
(the graph like star)

star_data <- datasaurus_dozen %>%
+     filter(dataset == "star")
 ggplot(data = star_data, mapping = aes(x = x, y = y)) +
+     geom_point() star_data %>%
+     summarize(r = cor(x, y))
# A tibble: 1 x 1
        r
    <dbl>
1 -0.0630

 datasaurus_dozen %>%
+     group_by(dataset) %>%
+     summarize(r = cor(x, y)) %>%
+     print(13)
# A tibble: 13 x 2
   dataset          r
 * <chr>        <dbl>
 1 away       -0.0641
 2 bullseye   -0.0686
 3 circle     -0.0683
 4 dino       -0.0645
 5 dots       -0.0603
 6 h_lines    -0.0617
 7 high_lines -0.0685
 8 slant_down -0.0690
 9 slant_up   -0.0686
10 star       -0.0630
11 v_lines    -0.0694
12 wide_lines -0.0666
13 x_shape    -0.0656